blogs/urls.py
from django.urls import path
from django.utils.translation import gettext_lazy as _
from . import views
from blogs import views as contact_views
from django.conf.urls import url, include, handler404, handler500

# APP NAME
app_name = 'blogs'
# URLS
urlpatterns = [
    path('about/', views.about_page, name='about'),

    path('news/', views.NewsListView.as_view(), name='news_list'),
    path('news/<int:year>/<int:month>/<int:day>/<slug:slug>/', views.NewsDetailView.as_view(), name='news_detail'),

    path('tender/', views.TenderListView.as_view(), name='tender_list'),
    path('tender/<int:year>/<int:month>/<int:day>/<slug:slug>', views.TenderDetailView.as_view(),
         name='tender_detail'),

    path('product/', views.ProductListView.as_view(), name='product_list'),
    path('product/<int:_id>/', views.ProductItemView, name='product_item'),

    path('membership/', views.MembershipListView.as_view(), name='membership_list'),
    path('membership/<slug:slug>', views.MembershipDetailView.as_view(), name='membership_detail'),

    path('exhibitions/', views.ExhibitionListView.as_view(), name='exhibition'),
    path('exhibitions/<int:year>/<int:month>/<int:day>/<slug:slug>', views.ExhibitionDetailView.as_view(),
         name='exhibition_detail'),

    path('gallery/', views.GalleryListView.as_view(), name='gallery'),
    path('gallery/<int:_id>/', views.GalleryImagesView, name='gallery-images'),

    path('search/', views.NewsSearchView.as_view(), name='news_search_url'),

    path('media/', views.MediaListView.as_view(), name='media'),

    path('vacancy/', views.VacancyListView.as_view(), name='vacancy'),

    path('faq/', views.FAQListView.as_view(), name='faq'),

    path('contact/', contact_views.contact_view, name='contact_form'),

    path('virtual_reception/', views.virtual_reception_view, name='virtual_reception_form'),

    path('entrepreneurs/', views.EntrepreneursListView.as_view(), name='entrepreneurs'),

    path('press_service/', views.press_service_view, name='press_service'),

    path('how_to_join/', views.join_view, name='how_to_join'),

    path('moscow/', views.moscow_view, name='moscow'),

    path('events/', views.events_view, name='events'),

    path('presentations/', views.presentations_view, name='presentations'),

    path('press_releases/', views.press_releases_view, name='press_releases'),

    path('publications/', views.publications_view, name='publications'),

    path('leadership/', views.leadership_view, name='leadership'),
    path('leadership_press/', views.leadership_press_view, name='leadership_press'),

    path('investors/', views.investors_view, name='investors'),

    path('exporters/', views.exporters_view, name='exporters'),

    path('youth_policy/', views.youth_policy_view, name='youth_policy'),

    path('structure/', views.structure_view, name='structure'),

    path('partners/', views.partners_view, name='partners'),

    path('foreighn_representation/', views.foreighn_view, name='foreighn_representation'),

    path('doc_links/', views.foreighn_representation_links, name='foreighn_representation_links'),
    path('doc_links/<slug>/', views.foreighn_representation_items, name='foreighn_representation_items'),

    path('subsidaries/', views.subsidaries_view, name='subsidaries'),

    path('subsidaries2/', views.subsidaries2_view, name='subsidaries2'),

    path('territorial_admin/', views.territorial_view, name='territorial_admin'),

    path('history_of_organization/', views.history_view, name='history_of_organization'),

    path('menu_companys/<type_slug>/', views.menu_companys_view, name='menu_companys'),

    path('menu_companys/', views.companys_types_view, name='companys_types'),

    path('membership_procedure/', views.MembershipProcedureListView.as_view(), name='membership_procedure'),

    path('benefits/', views.benefits_view, name='benefits'),

    path('investment_potential/', views.investmentadmin_view, name='investment_potential'),

    path('export_potential/', views.export_potential_view, name='export_potential'),

    path('export_implementation/', views.export_implementation_view, name='export_implementation'),

    path('export_law/', views.export_law_view, name='export_law'),

    path('market_entry_strategies/', views.market_entry_strategies_view, name='market_entry_strategies'),

    path('content/<slug:slug>', views.StaticContentView.as_view(), name='static_page'),

    path('legal/', views.LegalDocumentListView.as_view(), name='legal'),

    path('legal/<slug:slug>', views.LegalDocumentView.as_view(), name='legal_detail'),

    path('statistic/', views.StatisticListView.as_view(), name='statistic_list'),

    path('statistic/<slug:slug>', views.StatisticDetailView.as_view(), name='statistic_detail'),

    path('lex_uz/', views.lex_uz_view, name='lex_uz'),

     path('<branch_name>/', views.foreighn_branch_view, name='foreighn_representation_branch'),
    path('', views.index_page, name='index'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
from blogs.views import index_page

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('blogs.urls')),
    path('user/', include('users.urls')),
)

urlpatterns.append(path("", index_page))

urlpatterns += [
    path('rosetta/', include('rosetta.urls')),
    # path('captcha/', include('captcha.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

handler500 = 'blogs.views.error_500'
handler404 = 'blogs.views.error_404'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# admin.site.site_header = _('Uzcharmsanoat admin panel')
# admin.site.site_title = _('Uzcharmsanoat Admin Portal')
# admin.site.index_title = _('Welcome to Uzcharmsanoat Portal')

templates/blogs/pages/virtual_reception/virtual_reception_form.html
{% extends "users/base.html" %}
{% load i18n static %}

{% block css%}
<style>
      .card__header {
            text-align: center;
        }

        .card__header img {
            height: 100px;
        }
        .backto_home {
            display: flex;
            justify-content: center;
            align-items: center;
            text-decoration: none;
        }

        .backto_home a {
            text-decoration: none;
        }
        .body_c {
            background-color: rgb(228, 229, 247);
        }
        .online__reception{
            background-color: #fff;
            box-shadow: 2px 5px 20px rgba(0, 0, 0, 0.1);
            border-radius: 10px;
        }

</style>
{% endblock css %}

{% block main %}

<div class="body_c">

    <div class="container">
        <div class="row">

    
            <div class="col-md-12 my-5">
                <div class="card overflow-hidden online__reception border-0">
                    <div class="card__header">
                        {#<img src="{{ menu_settings.logo.url }}" class="brand__logo event-content" alt="logo">#}

                        <img src="https://static.tildacdn.com/tild3633-3563-4762-a631-376137353932/UZCHARMSANOAT_LOGO_1.jpg"
                             alt="">
                        <h3 class="text-center">{{ menu_settings.logo_text|safe }}</h3>
                    </div>
                    <form action="{% url 'blogs:virtual_reception_form' %}" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="card-body px-5 row">
    
                            <div class="col-md-6 my-3">
                                <label for="{{form.company_name.id}}">{{form.company_name.label}}</label>
                                {{form.company_name}}
                            </div>
    
                            <div class="col-lg-6 col-md-6 my-3">
                                <label for="{{form.email.id}}">{{form.email.label}}</label>
                                {{form.email}}
                            </div>
    
                            <div class="col-lg-6 col-md-6 my-3">
                                <label for="{{form.phone_number.id}}">{{form.phone_number.label}}</label>
                                {{form.phone_number}}
                            </div>
    
                            <div class="col-lg-6 col-md-6 my-3">
                                <label for="{{form.region.id}}">{{form.region.label}}</label>
                                {{form.region}}
                            </div>
    
                            <div class="col-lg-6 col-md-6 my-3">
                                <label for="{{form.address.id}}">{{form.address.label}}</label>
                                {{form.address}}
                            </div>
    
                            <div class="col-lg-12 col-md-12 my-3">
                                {{form.file_upload.label}}
                                {{form.file_upload}}
                            </div>
    
                            <div class="col-lg-12 my-3">
                                {{form.message.label}}
                                {{form.message}}
                            </div>
    
                            <div class="col-lg-12 my-3">
                                <div class="form-check">
                                    <input class="form-check-input input__form_con" type="checkbox" value=""
                                           id="defaultCheck1" required>
                                    <label class="form-check-label" for="defaultCheck1">
                                        {% trans 'Allow my question to be published' %}
                                    </label>
                                </div>
                            </div>
    
                            <div class="col-lg-3">
                                <button class="outline-none btn__send btn btn-primary">{% trans 'Send' %}</button>
                            </div>

                            {{form.errors}}
    
                        </div>
                    </form>
                    <div class="text-center mb-5 mt-0">
                        <a class="backto_home" href="{% url 'blogs:index' %}">
                            <i class="ri-arrow-left-s-line" style="margin-right: 7px;"></i>
                            {% trans 'Back to home' %}
                        </a>
                    </div>
                </div>
            </div>
          
        </div>
    </div>
    </div>
{% endblock %}