blogs/urls.py
from django.urls import path
from django.utils.translation import gettext_lazy as _
from . import views
from blogs import views as contact_views
from django.conf.urls import url, include, handler404, handler500

# APP NAME
app_name = 'blogs'
# URLS
urlpatterns = [
    path('about/', views.about_page, name='about'),

    path('news/', views.NewsListView.as_view(), name='news_list'),
    path('news/<int:year>/<int:month>/<int:day>/<slug:slug>/', views.NewsDetailView.as_view(), name='news_detail'),

    path('tender/', views.TenderListView.as_view(), name='tender_list'),
    path('tender/<int:year>/<int:month>/<int:day>/<slug:slug>', views.TenderDetailView.as_view(),
         name='tender_detail'),

    path('product/', views.ProductListView.as_view(), name='product_list'),
    path('product/<int:_id>/', views.ProductItemView, name='product_item'),

    path('membership/', views.MembershipListView.as_view(), name='membership_list'),
    path('membership/<slug:slug>', views.MembershipDetailView.as_view(), name='membership_detail'),

    path('exhibitions/', views.ExhibitionListView.as_view(), name='exhibition'),
    path('exhibitions/<int:year>/<int:month>/<int:day>/<slug:slug>', views.ExhibitionDetailView.as_view(),
         name='exhibition_detail'),

    path('gallery/', views.GalleryListView.as_view(), name='gallery'),
    path('gallery/<int:_id>/', views.GalleryImagesView, name='gallery-images'),

    path('search/', views.NewsSearchView.as_view(), name='news_search_url'),

    path('media/', views.MediaListView.as_view(), name='media'),

    path('vacancy/', views.VacancyListView.as_view(), name='vacancy'),

    path('faq/', views.FAQListView.as_view(), name='faq'),

    path('contact/', contact_views.contact_view, name='contact_form'),

    path('virtual_reception/', views.virtual_reception_view, name='virtual_reception_form'),

    path('entrepreneurs/', views.EntrepreneursListView.as_view(), name='entrepreneurs'),

    path('press_service/', views.press_service_view, name='press_service'),

    path('how_to_join/', views.join_view, name='how_to_join'),

    path('moscow/', views.moscow_view, name='moscow'),

    path('events/', views.events_view, name='events'),

    path('presentations/', views.presentations_view, name='presentations'),

    path('press_releases/', views.press_releases_view, name='press_releases'),

    path('publications/', views.publications_view, name='publications'),

    path('leadership/', views.leadership_view, name='leadership'),
    path('leadership_press/', views.leadership_press_view, name='leadership_press'),

    path('investors/', views.investors_view, name='investors'),

    path('exporters/', views.exporters_view, name='exporters'),

    path('youth_policy/', views.youth_policy_view, name='youth_policy'),

    path('structure/', views.structure_view, name='structure'),

    path('partners/', views.partners_view, name='partners'),

    path('foreighn_representation/', views.foreighn_view, name='foreighn_representation'),

    path('doc_links/', views.foreighn_representation_links, name='foreighn_representation_links'),
    path('doc_links/<slug>/', views.foreighn_representation_items, name='foreighn_representation_items'),

    path('subsidaries/', views.subsidaries_view, name='subsidaries'),

    path('subsidaries2/', views.subsidaries2_view, name='subsidaries2'),

    path('territorial_admin/', views.territorial_view, name='territorial_admin'),

    path('history_of_organization/', views.history_view, name='history_of_organization'),

    path('menu_companys/<type_slug>/', views.menu_companys_view, name='menu_companys'),

    path('menu_companys/', views.companys_types_view, name='companys_types'),

    path('membership_procedure/', views.MembershipProcedureListView.as_view(), name='membership_procedure'),

    path('benefits/', views.benefits_view, name='benefits'),

    path('investment_potential/', views.investmentadmin_view, name='investment_potential'),

    path('export_potential/', views.export_potential_view, name='export_potential'),

    path('export_implementation/', views.export_implementation_view, name='export_implementation'),

    path('export_law/', views.export_law_view, name='export_law'),

    path('market_entry_strategies/', views.market_entry_strategies_view, name='market_entry_strategies'),

    path('content/<slug:slug>', views.StaticContentView.as_view(), name='static_page'),

    path('legal/', views.LegalDocumentListView.as_view(), name='legal'),

    path('legal/<slug:slug>', views.LegalDocumentView.as_view(), name='legal_detail'),

    path('statistic/', views.StatisticListView.as_view(), name='statistic_list'),

    path('statistic/<slug:slug>', views.StatisticDetailView.as_view(), name='statistic_detail'),

    path('lex_uz/', views.lex_uz_view, name='lex_uz'),

     path('<branch_name>/', views.foreighn_branch_view, name='foreighn_representation_branch'),
    path('', views.index_page, name='index'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import gettext_lazy as _
from blogs.views import index_page

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('blogs.urls')),
    path('user/', include('users.urls')),
)

urlpatterns.append(path("", index_page))

urlpatterns += [
    path('rosetta/', include('rosetta.urls')),
    # path('captcha/', include('captcha.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

handler500 = 'blogs.views.error_500'
handler404 = 'blogs.views.error_404'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# admin.site.site_header = _('Uzcharmsanoat admin panel')
# admin.site.site_title = _('Uzcharmsanoat Admin Portal')
# admin.site.index_title = _('Welcome to Uzcharmsanoat Portal')

templates/blogs/pages/product/item.html
{% extends 'base.html' %}
{% load i18n static %}


{% block content %}
    <div class="wrap-body">
        <section class="all__pro" style="background-image: url({% static 'assets/images/bannerimg.png' %})">
            <div class="container h-100">
                <div class="row h-100">
                    <div class="col-md-12">
                        <div class="heading_pro-all">
                            <h1 class="font-weight-bold">{% trans 'All products' %}</h1>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <div class="container">
            <div class="row pt-5 mt-5">
        
                {% for item in products %}
                    <div class="col-lg-4 col-md-6 col-12 pro___card mb-5">
                        <div class="card__head h-100 bg-white shadow">
                            <div class="card border-0 card-fath">
                                <a data-fancybox="gallery" href="{{ item.image.url }}" data-aos="fade-down-right">
                                    <img class="image__proo" src="{{ item.image.url }}" alt="" style="border-radius: 0">
                                </a>
                            </div>
                            <div class="card-body-description px-4">
                                <h4>{{ item.title }}</h4>
                                <p>{{ item.main_text|safe }}</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/blogs/pages/product/product_list.html
{% extends 'base.html' %}
{% load i18n static %}


{% block css %}
<style>
.pro___card h5{
    opacity: 0;
    display: flex;
    align-items: center;
    justify-content: center;
    height: 100%;
    margin-bottom: 0;
    bottom: 0;
    transition: al.5s;
    /* color: transparent; */
}
.pro___card:hover h5{
    background: #000000b8;
    opacity: 1;
    color: #fff;
}
</style>
{% endblock css %}


{% block content %}
    <div class="wrap-body">
        <section class="all__pro" style="background-image: url({% static 'assets/images/bannerimg.png' %})">
            <div class="container h-100">
                <div class="row h-100">
                    <div class="col-md-12">
                        <div class="heading_pro-all">
                            <h1 class="font-weight-bold">{% trans 'Product Categories' %}</h1>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <div class="container">
            <div class="row pt-5 mt-5">
        
                {% for item in categories %}
                    <div class="col-lg-4 mb-4 col-md-6 col-12 pro___card mt-2">
                        <a class="text-decoration-none" href="{% url 'blogs:product_item' item.id %}">
                            <div class="shadow overflow-hidden position-relative text-center" style="border-radius: 20px;">
                            <img src="{{item.image.url}}" alt="{{ item.title }}">
            
                            <h5>{{ item.name }}</h5>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}